services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base # Development stage in multi-stage Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    restart: always # Automatically restart if container stops
    command: npm run dev # Runs Next.js dev server
    environment:
      NODE_ENV: development
    volumes:
      - .:/app # Mounts your local directory into the container
      - /app/node_modules # Avoid overwriting node_modules
      - /app/.next # Preserve Next.js build cache
