# Use a Node.js base image
FROM node:18-alpine AS base

# Install dependencies
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy the entire project
COPY . .

# Install WebDriverIO packages and dependencies
RUN npm install --save-dev @wdio/cli @wdio/mocha-framework @wdio/local-runner @wdio/spec-reporter @wdio/selenium-standalone-service chai @types/chai @types/mocha @types/node @types/webdriverio

# Install WebDriverIO dependencies
RUN npx wdio config --yes

# Install Chromium and ChromeDriver (the correct way)
RUN apk add --no-cache chromium chromedriver

# Set the PATH. This is the CRUCIAL STEP.
ENV PATH="/usr/bin:$PATH"

# Run tests
CMD ["npx", "wdio", "./wdio.conf.ts"]
