version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g # Prevents crashes due to insufficient shared memory
    ports:
      - "4444:4444"
