FROM node:18-bullseye AS base

# Install dependencies
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy the entire project
COPY . .

# Install WebDriverIO and necessary packages
RUN npm install --save-dev \
    @wdio/cli \
    @wdio/mocha-framework \
    @wdio/local-runner \
    @wdio/spec-reporter \
    chai @types/chai @types/mocha @types/node @types/webdriverio

# Install WebDriverIO dependencies
RUN npx wdio config --yes

# Install Chrome and dependencies
RUN apt-get update && apt-get install -y \
    chromium \
    libglib2.0-0 \
    libnss3 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libxkbcommon0 \
    ca-certificates \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Ensure chrome process isn't lingering
RUN pkill -f chrome || true

# Download and install ChromeDriver
RUN wget -O chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/134.0.6988.0/linux64/chromedriver-linux64.zip" \ 
    && unzip chromedriver.zip \
    && chmod +x chromedriver-linux64/chromedriver \
    && mv chromedriver-linux64/chromedriver /usr/bin/chromedriver \
    && rm -rf chromedriver.zip chromedriver-linux64/

# Verify ChromeDriver installation
RUN /usr/bin/chromedriver --version

# Set the PATH
ENV PATH="/usr/bin:$PATH"
ENV CHROME_BIN="/usr/bin/chromium"

# Run tests
CMD ["npx", "wdio", "./wdio.conf.ts"]

